#!/usr/bin/with-contenv sh
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
########  COMMANDS  ##########
PAGE=$(cat ${PLEX_AUTOSCAN_CONFIG} | grep -q '"PLEX_LOCAL_URL":' | awk -F\" '{print $4}')
TOKEN=$(cat ${PLEX_AUTOSCAN_CONFIG} | grep -q '"PLEX_TOKEN":' | awk -F: '{print $2}' | awk -F\" '{print $2}')

######## FUNCTIONS ##########
if [ -f ${PLEX_AUTOSCAN_CONFIG} ]
 ## PING PLEX ### COMMANDS ##
fi
